import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex">
        <nav className="w-48 h-screen bg-gray-800 text-white p-4">
          <Link href="/" className="block mb-4 hover:underline">Home</Link>
          <Link href="/projects" className="block hover:underline">Projects</Link>
        </nav>
        <main className="flex-1">{children}</main>
      </body>
    </html>
  )
}